"""agregar campo prioridad

Revision ID: 05702ef4b618
Revises: 58cbce442bf6
Create Date: 2025-10-19 01:26:47.872651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05702ef4b618'
down_revision: Union[str, Sequence[str], None] = '58cbce442bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('prioridad', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'prioridad')
    # ### end Alembic commands ###
