"""agregar campo prioridad

Revision ID: 05702ef4b618
Revises: 58cbce442bf6
Create Date: 2025-10-19 01:26:47.872651

⚠️ NOTA EDUCATIVA:
Esta migración añade una columna NOT NULL con server_default.
Esto es la forma correcta para permitir inserts sin especificar prioridad.

IMPORTANTE: En producción con tablas grandes, la estrategia óptima sería en 2 pasos:
1. Migration 1: ADD COLUMN prioridad INTEGER NULL DEFAULT 2
2. Migration 2: ALTER COLUMN prioridad SET NOT NULL (después de poblar datos)

Esta migración usa server_default para compatibilidad con los tests y funcionalidad real.

Ver Clase 4 - Sección "Migraciones en Producción" para estrategias zero-downtime.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05702ef4b618'
down_revision: Union[str, Sequence[str], None] = '58cbce442bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tareas',
        sa.Column('prioridad', sa.Integer(), nullable=False, server_default=sa.text('2'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'prioridad')
    # ### end Alembic commands ###
