# railway.toml
# Configuraci칩n para deploy en Railway
#
# Documentaci칩n: https://docs.railway.app/reference/config-as-code

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn api.api:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Variables de entorno
# Estas se configuran en el dashboard de Railway, NO en el c칩digo
# Railway proporciona DATABASE_URL autom치ticamente si agregas PostgreSQL
